### ISSUE TITLE
MCP server for agent

### ISSUE THREAD

**Issue by amolk** [playbooks-ai/playbooks#18]
`playbooks mcp-serve *.md OrderManagementAgent -p 5000` will start a new MCP server on port 5000 for the OrderManagementAgent agent loaded from *.md

May need to add playbooks executable if that doesn't exist

**Comment by amolk** [comment]
A better way might be to use agent metadata to specify this, e.g.

```
# My agent that will be MCP
protocol:
  type: mcp
  port: 9000
  path: /mcp
```

This would start an MCP server at http://localhost:9000/mcp that exposes all public playbooks as MCP tools

Consider how to expose multiple protocols like MCP and A2A
