### ISSUE TITLE
Register remote agents

### ISSUE THREAD

**Issue by amolk** [playbooks-ai/playbooks#20]
`# AuthenticationAgent(url="https://cloud.runplaybooks.ai/authentication", protocol="playbooks")`

`# AuthenticationAgent(url="https://cloud.runplaybooks.ai/authentication", protocol="mcp")`

This registers a remote agent at the given url. Later, public methods of this agent can be called, e.g. `AuthenticationAgent.Authenticate($email, $pin)`

Three protocols will be supported (implemented in dependent issues) -
- "playbooks" (default) use playbooks protocol
- "mcp" call tools
- "a2a" call tasks

**Comment by amolk** [comment]
Syntax for proxy agent for an MCP server -

```
# Git tools
This agent provides various python tools for interacting with git.
remote:
  type: mcp
  url: http://127.0.0.1:8888/mcp
  transport: streamable-http
```
